ITeens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from .views import *
from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('register/', register, name='register'),
    path('auth/', auth, name='auth'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/<str:id>', profile, name='profile'),
]

web/urls.py
from django.urls import path, include

from .views import *
from .apps import WebConfig

app_name = WebConfig.name


urlpatterns = [
    path('', homepage, name='homepage'),
    path('users/', users_view, name='users_view'),
    path('vacancies/', vacancies_view, name='vacancies_view'),
    path('resumes/', resumes_view, name='resumes_view'),
    path('chats/', chats_view, name='chats_view'),
    path('chats/create', chats_create, name='chat_create'),
    path('chats/<str:chat_id>', chat_view, name='chat_view'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    STUDENT = 's'
    EMPLOYER = 'e'
    CHOICES = [
        (STUDENT, 'student'),
        (EMPLOYER, 'employer')
    ]
    first_name = models.CharField(verbose_name="Имя", max_length=20)
    last_name = models.CharField(verbose_name="Фамилия", max_length=30)
    email = models.EmailField(verbose_name="Электронная почта", max_length=100, unique=True)
    profile_pic = models.ImageField(verbose_name="Фотография", upload_to="users_photo", null=True, blank=True,
                                    default="../static/defaultPhoto.png")
    description = models.CharField(max_length=256, null=True, blank=True, verbose_name='Описание профиля')
    city = models.CharField(max_length=16, verbose_name='Город проживания')
    phone_number = models.CharField(max_length=16, verbose_name='Номер телефона')
    role = models.CharField(max_length=1, choices=CHOICES, default=STUDENT)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.email)

web/models.py
from django.db import models
from django import template
from users.models import CustomUser
from django.utils import timezone


class Resume(models.Model):
    name = models.CharField("name", max_length=32)
    description = models.CharField("description", max_length=512)
    skills = models.ManyToManyField('Skill', related_name='skills')
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=150, unique=True, blank=True, null=True, verbose_name='Ссылка на профиль')

    def __str__(self):
        return str(self.name)


class Vacancy(models.Model):
    name = models.CharField("name", max_length=64)
    description = models.CharField("description", max_length=512)
    place = models.CharField("place", max_length=128)
    wage = models.FloatField('wage')
    skills = models.ManyToManyField('Skill')
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Skill(models.Model):
    SOFT = 's'
    HARD = 'h'
    CHOICES = [
        (SOFT, 'soft'),
        (HARD, 'hard')
    ]
    type = models.CharField(max_length=1, choices=CHOICES, default=HARD)
    name = models.CharField("name", max_length=16)

    def __str__(self):
        return str(self.name)


class Chat(models.Model):
    members = models.ManyToManyField(CustomUser, verbose_name='Участник')


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name="Чат", on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, verbose_name='Автор', on_delete=models.CASCADE)
    message = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.message

users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=36, widget=forms.PasswordInput(), label="Пароль")
    password2 = forms.CharField(max_length=36, widget=forms.PasswordInput(), label='Повторите пароль')

    class Meta:
        model = CustomUser
        fields = 'first_name', 'last_name', 'email', 'profile_pic', 'city', 'phone_number', 'role'

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError('Пароли не совпадают')
        return self.cleaned_data['password1']


class AuthForm(forms.Form):
    email = forms.EmailField(max_length=36, label="Email")
    password = forms.CharField(max_length=36, widget=forms.PasswordInput(), label="Пароль")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import *
from .forms import *


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            redirect('users:auth')
    return render(request, 'register.html', {'form': form})


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=36, widget=forms.PasswordInput(), label="Пароль")
    password2 = forms.CharField(max_length=36, widget=forms.PasswordInput(), label='Повторите пароль')

    class Meta:
        model = CustomUser
        fields = 'first_name', 'last_name', 'email', 'profile_pic', 'city', 'phone_number', 'role'

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError('Пароли не совпадают')
        return self.cleaned_data['password1']


def auth(request):
    form = AuthForm()
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                request.session['pk'] = user.pk
                login(request, user)
                redirect('users:profile')
            else:
                messages.error(request, 'Неправильный логин или пароль, повторите попытку входа')
    return render(request, 'auth.html', {'form': form})


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('users:auth')
    return render(request, 'logout.html')


@login_required
def profile(request, id):
    user = CustomUser.objects.filter(id=id)
    return render(request, 'profile.html', {'user': user})

web/templates/base.html
{% load static %}

{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}ITeens{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"
                 src="../../static/defaultPhoto.png" alt=""/>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% block navbar_buttons %}
                 <li><a href="#" class="nav-link px-2 text-white">О нас</a></li>
            {% endblock %}
        </ul>
<!-- searchbar
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        -->

        <div class="text-end">
        <div class="text-end">
          <!-- todo notif button-->
            {% if isAuth %}
                <button type="button" class="btn btn-outline-secondary me-2">Notifications</button>
                <button type="button" class="btn btn-outline-success">Profile</button>
            {% else %}
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-success">Sign-up</button>
            {% endif %}
        </div>
      </div>
    </div>
    </div>
  </header>{% block content %}

{% endblock %}
</body>
</html>

web/templates/chat_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web/templates/chats_view.html
{% extends "base.html" %}

{% block title %}Чаты {% endblock %}

{% block content %}

    <div class="panel">
        {% load tz %}
        {% load tags %}
        {% if chats.count == 0 %}
            <div class="panel panel-body">Нет ни одного начатого диалога</div>
        {% endif %}
        {% for chat in chats %}
            {% if chat.message_set.count != 0 %}
                {% with last_message=chat.message_set.last %}
                    {% get_companion user chat as companion %}
                    <a class="list-group-item {% if companion == last_message.author and not last_message.is_read %}unread{% endif %}" href="{% url 'web:chat_view' chat.id %}">
                        <img class="avatar-messages" src="{{ companion.userprofile.get_avatar }}">
                        <div class="reply-body">
                            <ul class="list-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                </li>
                                <li class="pull-right text-muted"><small>{{ last_message.pub_date|utc }}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <img class="avatar-rounded-sm" src="{{ last_message.author.userprofile.get_avatar }}">
                                    <div class="attached-reply-body {% if not last_message.is_read %}unread{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

{% block navbar_buttons %}
    <li><a href="#" class="nav-link px-2 text-white">О нас</a></li>
    <li><a href="#" class="nav-link px-2" style="color: white; background-color: green; border-radius: 3px;">Создать вакансию</a></li>
{% endblock %}

web/templates/create_chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web/templates/resumes_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web/templates/users_view.html
{% extends 'base.html' %}

{% block title %}Пользователи{% endblock %}

{% block content %}

    {% for user in users %}
    <div class="container">
        <div class="card" style="width: 18rem;" href="{% url 'users:profile' user.id%}">
            <a href="{% url 'users:profile' user.id %}" style="text-decoration: none; color:#000000">
          <img src="{{ user.profile_pic.url}}"  class="card-img-top" alt="...">
          <div class="card-body">
              <h5 class="card-title">{{ user.username }}</h5>
            <p class="card-text">{{ user.first_name }} {{ user.last_name }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ user.phone_number }}</li>
            <li class="list-group-item">{{ user.city }}</li>
            <li class="list-group-item">{{ user.school }}</li>
          </ul>
            </a>
    </div>
    </div>
    {% endfor %}

    <div class="container">

    </div>
{% endblock %}

{% block navbar_buttons %}
    <li><a href="#" class="nav-link px-2 text-white">О нас</a></li>
    <li><a href="#" class="nav-link px-2" style="color: white; background-color: green; border-radius: 3px;">Создать вакансию</a></li>
{% endblock %}

web/templates/vacancies_view.html
{% extends 'base.html' %}

{% block title %}Резюме{% endblock %}

{% block content %}

    <!--todo-->
    <script>
        function changeLabels()
        {
            document.getElementById("minLabel").innerText=document.getElementById('wageMin').value;
            document.getElementById("maxLabel").innerText=document.getElementById('wageMax').value;
        }
    </script>

    {% for vacancy in vacancies %}
    <div class="container">
     <!-- todo href-->
        <div class="card" style="width: 18rem;">
          <div class="card-body">
              <h5 class="card-title">{{ vacancy.name }}</h5>
            <p class="card-text">{{ vacancy.owner.username }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ vacancy.description|truncatechars:20 }}</li>
              {% for skill in vacancy.skills.all %}
            <li class="list-group-item">{{ skill.name }}</li>
              {% endfor %}
          </ul>
    </div>
    </div>
    {% endfor %}

    <form class="container" style="width: 20%;">
        <label for="customRange3">  Зарплата минимум  </label>
        <p id="minLabel">20000</p>
            <input type="range" onmousemove="changeLabels()" class="form-range" min="20000" max="495000" step="5000" value="20000" name="wageMin" id="wageMin" >

        <p id="maxLabel">500000</p>
        <label for="customRange3">  Зарплата максимум </label>
            <input type="range"  onmousemove="changeLabels()" class="form-range" min="25000" max="500000" step="5000" value="500000" name="wageMax" id="wageMax"  >

     <button type="submit" class="btn btn-outline-secondary">Secondary</button>

    </form>


{% endblock %}